---
title: "lab13"
author: "allstars"
date: "11/19/2019"
output: html_document
---

## Individual Sections

### Eugene Miller
```{r, setup}
library(tidyverse)
library(gapminder)

energy_capita <- read_csv('energy_production_per_person.csv')
flood_affected <- read_csv('flood_affected_annual_number.csv')

a <- which(colnames(energy_capita)=="1960")
b <- which(colnames(energy_capita)=="2010")

energy_capita <- energy_capita %>% 
  gather(a:b, key = "Year", value = "Energy Per Capita") %>%
  filter(!is.na(`Energy Per Capita`))

a <- which(colnames(flood_affected)=="1970")
b <- which(colnames(flood_affected)=="2008")

flood_affected <- flood_affected %>% 
  gather(a:b, key = "Year", value = "Flood Affected") %>% 
  filter(!is.na(`Flood Affected`))

data <- full_join(flood_affected,energy_capita, by = c("country", "Year")) %>%
  filter(!is.na(`Energy Per Capita`)) %>% 
  filter(!is.na(`Flood Affected`))

data$Year <- as.numeric(data$Year)

gap_new <- gapminder %>% 
  select(`country`, `year`, `pop`) %>%
  rename("Year" = `year`)

data <- full_join(data, gap_new, by = c("country", "Year")) %>%
  filter(!is.na(pop)) %>% 
  mutate(Flood_cap = `Flood Affected`/`pop`) %>% 
  filter(!is.na(Flood_cap))

data %>% map(summary)

r_flood <- map(data$Flood_cap, function(x) rnorm(10, x, 1))
r_energy <- map(data$`Energy Per Capita`, function(x) rnorm (10, x, 1))

# r_test <- tibble(
#  ~r_flood, ~r_energy,
#  for (i in seq_along(r_flood)){
#    flood_samp <- r_flood[[i]][[sample(1:10,1)]]
#    energy_samp <- r_energy[[i]][[sample(1:10,1)]]
#    flood_char <- as.character(flood_samp)
#    energy_char <- as.character(energy_samp)
#    comma = ",
#    "
#    paste(flood_char,energy_char,comma, sep = ",")
#  }
# )
```



```{r, message = F, echo = T, message = F, eval = T}

perm_cor <- function(perms = 1000, x, y)
{
  vec <- numeric(perms)
  for (i in c(1:perms))
  {
    r_Y <- sample(y)
    vec[i] <- cor(x, r_Y)
  }
  return(vec)
}


core <- cor( data$`Energy Per Capita`, data$`Flood_cap`)
corellate <- perm_cor(perms = 100000, data$`Energy Per Capita`,  data$`Flood_cap`)


ggplot() + aes(corellate)+ geom_histogram(binwidth=.01, colour="black", fill="white") + geom_vline(mapping =aes(xintercept=core), color = "red") + labs(x = "Correlation Tests")

p_value <- sum(corellate < core)/100000
p_value
```